# This name is reported to the client and shown in some dialogs
name: 'Spirit Server'

# The server will report this as the hostname of the Spirit server.
# If left undefined, will default to the system hostname.
#hostname: 'spirit.local'

# Local path to the repository, relative to rack start directory
repository_root: './ds_repo'

# Server version reported to the client, should match if you don't want
# warnings.
version: '1.6.12'

# Our version number, prefixed with the DS server version it emulates
spirit_version: '1.6.12.1'

# Admin credentials - Eventually this will tie into some actual authentication
# service
username: 'admin'
password: 'secret'

# Response format - Changed to binary sometime around 1.6.8
# If not true, reverts to xml encoded property lists.
respond_binary: True

# The OS X minor version to report that this system is running.
# Default 9 (10.9)
host_system_version: 9

# Runtime configuration of repository mounts
type: localtoserver
url: "afp://spirit.local/DS_Repo"

path_to_temporary_repository: /tmp/DSTemporaryMount
path_to_temporary_mount_point: /tmp/DSTemporaryMount
temporary_mount_command:
  command: /sbin/mount_afp
  arguments:
    - "-o"
    - "nobrowse"
    - "afp://admin:secret@spirit.local/DS_Repo"
    - "/tmp/DSTemporaryMount"

path_to_repository: /tmp/DSNetworkRepository
path_to_mount_point: /tmp/DSNetworkRepository
mount_command:
  command: /sbin/mount_afp
  arguments:
    - "-o"
    - "nobrowse"
    - "afp://admin:secret@spirit.local/DS_Repo"
    - "/tmp/DSNetworkRepository"

path_to_master_repository: /tmp/DSMasterMount
path_to_master_mount_point: /tmp/DSMasterMount
master_mount_command:
  command: /sbin/mount_afp
  arguments:
    - "-o"
    - "nobrowse"
    - "afp://admin:secret@spirit.local/DS_Repo"
    - "/tmp/DSMasterMount"